charity_project/alpha/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('charity.urls', namespace='charity')),
    path('', include('users.urls', namespace='users')),
]

charity_project/charity/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views as cv


app_name = 'charity'


urlpatterns = [
    path('', cv.LandingPage.as_view(), name="landing-page"),
    path('add_donation/', cv.AddDonation.as_view(), name="add-donation"),
    # path('login/', cv.Login.as_view(), name="login"),
    path('login/', cv.LoginView.as_view(), name="login"),
    path('logout/', cv.LogoutView.as_view(), name="logout"),
    path('register/', cv.Register.as_view(), name="register"),
    path('reset_password/', cv.ResetPassword.as_view(), name="reset-password"),
    path('user_profile/', cv.UserProfile.as_view(), name="user-profile"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

charity_project/users/urls.py
from . import views as uv

app_name = 'users'

urlpatterns = [

]

charity_project/charity/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Institution(models.Model):
    INSTITUTION_TYPES = [
        ('fundacja', 'Fundacja'),
        ('organizacja', 'Organizacja pozarządowa'),
        ('zbiorka', 'Zbiórka lokalna'),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    type = models.CharField(max_length=30, choices=INSTITUTION_TYPES, default='fundacja')
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name + ' ---- ' + self.description


class Donation(models.Model):
    quantity = models.PositiveIntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address_street = models.CharField(max_length=255)
    address_number = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=10)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.TextField()
    user = models.ForeignKey(User, null=True, default=True,  on_delete=models.SET_NULL)

    def __str__(self):
        return f"Dar nr {self.pk}"

charity_project/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,BaseUserManager
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return f'{self.username} ({self.email})'

    objects = UserManager()

charity_project/charity/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

charity_project/charity/views.py
from django.db.models import Sum
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic import ListView, FormView, RedirectView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.contrib import messages
from .models import Donation, Institution
from .forms import NewUserForm

User = get_user_model()


class LandingPage(View):
    def get(self, request, *args, **kwargs):
        donated_bags = Donation.objects.aggregate(total_bags=Sum('quantity'))['total_bags']
        supported_organizations = Institution.objects.count()
        foundations = Institution.objects.filter(type__contains='fundacja')
        organisations = Institution.objects.filter(type__contains='organizacja')
        fundraisers = Institution.objects.filter(type__contains='zbiorka')

        context = {
            'donated_bags': donated_bags,
            'supported_organizations': supported_organizations,
            'foundations': foundations,
            'organisations': organisations,
            'fundraisers': fundraisers,
        }
        return render(request, "charity/index.html", context)


class LoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'charity/login.html'

    def get_success_url(self):
        return reverse_lazy('charity:landing-page')

    def form_invalid(self, form):
        email = form.cleaned_data.get('email')
        user = User.objects.filter(email=email).exists()

        if not user:
            # Jeśli użytkownik nie istnieje, przekieruj na stronę rejestracji
            messages.error(self.request, 'Nie masz konta w naszym serwisie. Zarejstruj się.' )
            return redirect('charity:register')

        return super().form_valid(form)


class LogoutView(RedirectView):
    url = reverse_lazy("charity:landing-page")

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class Register(CreateView):
    model = User
    template_name = 'charity/register.html'
    form_class = NewUserForm

    def get_success_url(self):
        return reverse_lazy('charity:login')

    def form_invalid(self, form):
        messages.error(self.request, 'Wypełnij poprawnie wszystkie pola w formularzu.')
        return self.render_to_response(self.get_context_data(form=form,))


class ResetPassword(View):
    def get(self, request, *args, **kwargs):
        return render(request, "charity/reset-password.html", {})


class AddDonation(LoginRequiredMixin, View):
    login_url = "/login/"
    redirect_field_name = "redirect_to"

    def get(self, request, *args, **kwargs):
        return render(request, "charity/form.html", {})


class UserProfile(View):
    def get(self, request, *args, **kwargs):
        return render(request, "charity/user_profile.html", {})

charity_project/users/views.py
from django.shortcuts import render

# Create your views here.

charity_project/charity/templates/charity/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'charity/css/style.css' %} " />
  </head>
  <body>

      <header class="{% block header-class %} {% endblock %}">
      <nav class="container container--70">
        <ul class="nav--actions">
          {% include 'charity/includes/base-nav-login-links.html' %}
        </ul>

        <ul>
          {% include 'charity/includes/base-nav-links.html' %}
        </ul>
      </nav>
  {% block header %}
  {% endblock %}
      </header>


  {% block content %}
  {% endblock %}

  {% include 'charity/includes/base-footer.html' %}

  <script src="{% static 'charity/js/app.js' %}"></script>

  </body>
</html>

charity_project/charity/templates/charity/form-confirmation.html
<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="css/style.css" />
  </head>
  <body>
    <header class="header--form-page">
      <nav class="container container--70">
        <ul class="nav--actions">
          <li class="logged-user">
            Witaj Agata
            <ul class="dropdown">
              <li><a href="#">Profil</a></li>
              <li><a href="#">Moje zbiórki</a></li>
              <li><a href="#">Wyloguj</a></li>
            </ul>
          </li>
        </ul>

        <ul>
          <li><a href="index.html" class="btn btn--without-border active">Start</a></li>
          <li><a href="index.html#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="index.html#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="index.html#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
          <li><a href="index.html#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>
      </nav>

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza Na maila prześlemy wszelkie
            informacje o odbiorze.
          </h2>
      </div>
    </header>

    <footer>
      <div class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50">
            <input type="text" name="name" placeholder="Imię" />
          </div>
          <div class="form-group form-group--50">
            <input type="text" name="surname" placeholder="Nazwisko" />
          </div>

          <div class="form-group">
            <textarea
              name="message"
              placeholder="Wiadomość"
              rows="1"
            ></textarea>
          </div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="images/icon-facebook.svg"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="images/icon-instagram.svg"
          /></a>
        </div>
      </div>
    </footer>

    <script src="js/app.js"></script>
  </body>
</html>

charity_project/charity/templates/charity/form.html
{% extends "charity/base.html" %}
{% load static %}

{% block title %} Form {% endblock %}

{% block header-class %} header--form-page {% endblock %}
{% block header %}
      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
{% endblock %}

{% block content %}

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

        <form action="form-confirmation.html" method="post">
          <!-- STEP 1: class .active is switching steps -->
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>

            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="clothes-to-use"
                />
                <span class="checkbox"></span>
                <span class="description"
                  >ubrania, które nadają się do ponownego użycia</span
                >
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input
                  type="checkbox"
                  name="categories"
                  value="clothes-useless"
                />
                <span class="checkbox"></span>
                <span class="description">ubrania, do wyrzucenia</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="toys" />
                <span class="checkbox"></span>
                <span class="description">zabawki</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="books" />
                <span class="checkbox"></span>
                <span class="description">książki</span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="checkbox" name="categories" value="other" />
                <span class="checkbox"></span>
                <span class="description">inne</span>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

            <div class="form-group form-group--inline">
              <label>
                Liczba 60l worków:
                <input type="number" name="bags" step="1" min="1" />
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>



          <!-- STEP 4 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="organization" value="old" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">Fundacja “Bez domu”</div>
                  <div class="subtitle">
                    Cel i misja: Pomoc dla osób nie posiadających miejsca
                    zamieszkania
                  </div>
                </span>
              </label>
            </div>

            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="organization" value="old" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div class="title">Fundacja “Dla dzieci"</div>
                  <div class="subtitle">
                    Cel i misja: Pomoc osobom znajdującym się w trudnej sytuacji
                    życiowej.
                  </div>
                </span>
              </label>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica <input type="text" name="address" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Miasto <input type="text" name="city" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy <input type="text" name="postcode" />
                  </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu <input type="phone" name="phone" />
                  </label>
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data <input type="date" name="data" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina <input type="time" name="time" /> </label>
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                    <textarea name="more_info" rows="5"></textarea>
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 6 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text"
                      >4 worki ubrań w dobrym stanie dla dzieci</span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text"
                      >Dla fundacji "Mam marzenie" w Warszawie</span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li>Prosta 51</li>
                    <li>Warszawa</li>
                    <li>99-098</li>
                    <li>123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li>13/12/2018</li>
                    <li>15:40</li>
                    <li>Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>

    <script src="js/app.js"></script>

{% endblock %}

charity_project/charity/templates/charity/includes/base-footer.html
{% load static %}
<footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
          <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię" /></div>
          <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko" /></div>

          <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

          <button class="btn" type="submit">Wyślij</button>
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"><img src="{% static 'charity/images/icon-facebook.svg' %}"/></a>
          <a href="#" class="btn btn--small"><img src="{% static 'charity/images/icon-instagram.svg' %}"/></a>
        </div>
      </div>
    </footer>

charity_project/charity/templates/charity/includes/base-nav-links.html
{% load static %}
{% load custom_tags %}
<li><a href="{% url 'charity:landing-page' %}" class="btn btn--without-border active">Start</a></li>
<li><a href="{% anchor 'charity:landing-page' 'steps' %}" class="btn btn--without-border">O co chodzi?</a></li>
<li><a href="{% anchor 'charity:landing-page' 'about-us' %}" class="btn btn--without-border">O nas</a></li>
<li><a href="{% anchor 'charity:landing-page' 'help' %}" class="btn btn--without-border">Fundacje i organizacje</a></li>
<li><a href="{% url 'charity:add-donation' %}" class="btn btn--without-border">Przekaż dary</a></li>
<li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>

charity_project/charity/templates/charity/includes/base-nav-login-links.html
{% load static %}

  {% if request.user.is_authenticated  %}
              <li class="logged-user">
            Witaj {{user.first_name }}
            <ul class="dropdown">
              <li><a href="{% url 'charity:user-profile' %}">Profil</a></li>
              <li><a href="#">Ustawienia</a></li>
                {% if request.user.is_superuser %}
              <li><a href="/admin">Panel administracyjny</a></li>
                {% endif %}
              <li><a href="{% url 'charity:logout' %}">Wyloguj</a></li>
            </ul>
          </li>

  {% else %}
<li><a href="{% url 'charity:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
<li><a href="{% url 'charity:register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>

  {% endif %}

charity_project/charity/templates/charity/login.html
{% extends "charity/base.html" %}
{% load static %}

{% block title %} Login {% endblock %}

{% block content %}

{% block header %}
{% endblock %}

    <section class="login-page">
      <h2>Zaloguj się</h2>
      <h1 style="color: darkorange">{{ error_message }}</h1>
      <h1>
        {% if messages %}
		{% for message in messages %}
			{{ message }}
		{% endfor %}
		{% endif %}
      </h1>

      <form action="{% url 'charity:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input type="email" name="username" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
          <a href="{% url 'charity:reset-password' %}" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'charity:register' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zaloguj się</button> 
        </div>
      </form>
    </section>

{% endblock %}

charity_project/charity/templates/charity/register.html
{% extends "charity/base.html" %}
{% load static %}

{% block title %} Login {% endblock %}

{% block content %}

{% block header %}
{% endblock %}

    <section class="login-page">
      <h2>Załóż konto</h2>
      <h1 style="color: darkorange">
        {% if messages %}
    {% for message in messages %}
        {%  if forloop.first  %}
                {{ message }}
        {% endif %}
    {% endfor %}
{% endif %}

      </h1>

      <form action="{% url 'charity:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="first_name" placeholder="Imię" />
        </div>
         <div class="form-group">
          <input type="text" name="last_name" placeholder="Nazwisko" />
        </div>
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password1" placeholder="Hasło" />
        </div>
        <div class="form-group">
          <input type="password" name="password2" placeholder="Powtórz hasło" />
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'charity:login' %}" class="btn btn--without-border">Zaloguj się</a>
          <button class="btn" type="submit">Załóż konto</button>
        </div>
      </form>
    </section>

{% endblock %}

charity_project/charity/templates/charity/reset-password.html
{% extends "charity/base.html" %}
{% load static %}

{% block title %} Reset Password {% endblock %}

{% block content %}

{% block header %}
{% endblock %}

    <section class="login-page">
      <h2>Zresetuj swoje hasło</h2>
      <form>
        <div class="form-group">
          <input type="email" name="email" placeholder="Email" />
        </div>
        <div class="form-group">
          <input type="password" name="password" placeholder="Hasło" />
<!--          <a href="#" class="btn btn&#45;&#45;small btn&#45;&#45;without-border reset-password">Przypomnij hasło</a>-->
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'charity:register' %}" class="btn btn--without-border">Załóż konto</a>
          <button class="btn" type="submit">Zresetuj hasło</button>
        </div>
      </form>
    </section>

{% endblock %}

charity_project/charity/templates/charity/user_profile.html
{% extends "charity/base.html" %}
{% load static %}

{% block title %} User profile {% endblock %}

{% block content %}

{% block header %}
{% endblock %}

    <section class="login-page">
      <h2>Profil użytkownika</h2>
        <p>Imię: {{user.first_name }}</p>
        <p>Nazwisko: {{user.last_name }}</p>
        <p>Email: {{user.email }}</p>
        <p>Użytkownik: {{user.username }}</p>
    </section>

{% endblock %}